### PR TITLE
Not only new, but also learning

### PR DESCRIPTION
**Pull request by ankitest**
This will make the supplement scope a little wider.

### CODE REVIEW

**Comment by glutanimate** [comment]
Good idea, thanks!

**Comment by omega3** [comment]
I tested it and it didn't work for me for old cards. I had a deck when old cards are reviewed in the first place and than new. Only when I went through all old and started new cards add-on started showing additional buttons. 

Please read it 
https://github.com/steveaw/anki_addons/issues/2

**Comment by glutanimate** [comment]
@omega3 This change only applies to cards in learning. Enabling the buttons for old cards, i.e. cards that are in review, would be more complicated as we would have to adapt the intervals to the existing interval of the cards. Otherwise you would end up in situations where the regular answer keys would schedule the cards to a larger interval than the extra buttons.

**Comment by ankitest** [comment]
@omega3 You can try to use: https://ankiweb.net/shared/info/755044381
~ More Answer Buttons for ALL Cards
No answer will be given, just apply additional interval.
SWAP_TAG may be assigned.

**Pull request merged**
